update

diff --git a/.github/workflows/cicd-v1.1.yaml b/.github/workflows/cicd-v1.1.yaml
--- a/.github/workflows/cicd-v1.1.yaml
+++ b/.github/workflows/cicd-v1.1.yaml
@@ -108,3 +108,26 @@ jobs:
           service: ${{ env.ECS_SERVICE_NAME }}
           cluster: ${{ env.ECS_CLUSTER_NAME }}
           wait-for-service-stability: true
+
+  health-check:
+    needs: deploy
+    runs-on: ubuntu-latest
+    steps:
+      - name: Wait for deployment to stabilize
+        run: sleep 30  # Adjust the sleep time as necessary to allow the app to start
+
+      - name: Health Check
+        run: |
+          URL="https://dev.tungphongdo89.click/health-check"
+          for i in {1..10}; do
+            STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
+            if [ $STATUS -eq 200 ]; then
+              echo "Health check passed!"
+              exit 0
+            else
+              echo "Health check failed with status $STATUS. Retrying in 10 seconds..."
+              sleep 10
+            fi
+          done
+          echo "Health check failed after multiple attempts."
+          exit 1
